### ISSUE TITLE
How to implement a connection to a server using SOCKS5 over TLS？

### ISSUE THREAD

**Issue by wanliyunyan** [LacticWhale/socks_dart#13]

**Comment by LacticWhale** [comment]
I cannot test this right now. But it seems like this will require to rewrite to whole connection class. 
You can check out `secure` branch in this repo. 
```yaml
     socks5_proxy:
       git:
         url: git://github.com/lacticwhale/socks_dart.git
         ref: secure
```
